import React from "react";
import { StyleSheet, Text, View } from "react-native";
import QRCodeScanner from "react-native-qrcode-scanner";

console.log("loaded");

export default class QRScanningScreen extends React.Component {
  state = {
    username: "",
    otherUsername: ""
  };
  WebRTCConnection = null;
  handleBarCodeScanned = readed => {
    const username = JSON.parse(readed.data)[1];
    const otherUsername = JSON.parse(readed.data)[0];
    const sigServer = this.props.navigation.getParam("sigServer");
    this.props.navigation.navigate("Pairing", {
      username,
      otherUsername,
      sigServer
    });
  };

  render() {
    return (
      <View style={styles.container}>
        <Text style={{ color: "white", fontSize: 18 }}>
          Scan QRCode generated by controller
        </Text>
        <QRCodeScanner onRead={e => this.handleBarCodeScanned(e)} />
      </View>
    );
  }
}

const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: "black",
    alignItems: "center",
    justifyContent: "center"
  },
  QRScanner: {
    height: "100%",
    width: "100%"
  }
});
